name: Deploy to Azure Static Web Apps

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
    branches: [main]
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: "azure-deploy"
  cancel-in-progress: true

permissions:
  actions: read # needed to download artifacts from other workflows

jobs:
  deploy:
    name: 🚀 Deploy to Azure Static Web Apps
    # Only run if CI workflow was successful
    if: |
      github.event.workflow_run.conclusion == 'success' ||
      github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    environment:
      name: production
      url: ${{ steps.deploy.outputs.static_web_app_url }}
    
    steps:
      - name: 📥 Download build artifacts
        uses: dawidd6/action-download-artifact@v11
        with:
          workflow: ci.yml
          name: azure-swa-build
          path: dist
          workflow_conclusion: success

      - name: 📋 List build contents
        run: ls -la dist/

      - name: 🚀 Deploy to Azure Static Web Apps
        id: deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          # Required
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GENTLE_GROUND_04EB9DE03 }}
          action: "upload" # Required: specify upload action for deployment
          app_location: "dist" # The location of your built app files
          
          # Optional configurations
          skip_app_build: true # Skip build since we already have built files
          skip_api_build: true # Skip API build since we don't have an API
          output_location: "" # Leave empty since files are already in correct structure
          production_branch: "main" # Specify the production branch
          deployment_environment: "production" # Specify the deployment environment
        env:
          # Add any environment variables your app needs at runtime
          VITE_APP_VERSION: ${{ github.event.workflow_run.head_branch || github.ref_name }}