name: Deploy to GitHub Pages

on:
  # workflow_run:
  #   workflows: ["CI"]
  #   types: [completed]
  #   branches: [main]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN
permissions:
  contents: read
  pages: write
  id-token: write
  actions: read # needed to download artifacts

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    name: 🚀 Deploy to GitHub Pages
    # Only run if CI workflow was successful
    if: |
      github.event.workflow_run.conclusion == 'success' ||
      github.event_name == 'workflow_dispatch'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    
    steps:
      - name: 📥 Download build artifacts
        uses: dawidd6/action-download-artifact@v11
        with:
          workflow: ci.yml
          name: github-pages-build
          path: dist
          workflow_conclusion: success
          
      - name: 🔧 Configure headers
        run: |
          cp public/_headers dist/
          # Ensure proper base path in all html files
          find dist -type f -name "*.html" -exec sed -i 's|<head>|<head><base href="/terpene-explorer/">|' {} +
          
      - name: 📋 List build contents
        run: ls -la dist/
      
      - name: 🔧 Setup Pages
        uses: actions/configure-pages@v5
      
      - name: 📦 Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: 'dist'
      
      - name: 🚀 Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4