name: PR Build

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Node.js
      uses: actions/setup-node@v6
      with:
        node-version: '24' # Or your preferred Node.js version

    - name: Install dependencies
      run: npm ci

    - name: Run unit tests
      run: npm test -- --watchAll=false

    - name: Run security audit
      run: npm audit

    - name: Run linting
      run: npm run lint # Assuming you have a lint script in package.json
